language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test -- --coverage
- yarn run sendcoverage
before_deploy:
- yarn build -- --declaration
deploy:
  provider: npm
  on:
    branch: master
  skip_cleanup: true
  email:
    secure: 0KgOVda1qTHpIyqG5ZNh2vPsTeF6dXRLYDFh38wFmsmYpo1a0PXbTKv9uZ3LzdBdurcWwBUC0HotKBcn91s40zrtovDTZfg11uDwq+fx23cDsf91WiQjD3s1WLWKXYwULsmm4H00wTfbWKd42CHMkvH8ObhnN1fAKyYn0yqcvgd/xYI2WZ0d8pEkvofAFUSaNC/4D6VQ+ETSt/+a6aQpqgHW2AuxlCuc7N5vFLQH7r+wsJaEZ913DelB1579mFSM45JtK5tKn4SYxb3aQkV+vYSRr+Gf+Hna/hJPgJAThggGbJpCnY/QmNHR/7RaktlpoDXpKEq9IEzQ8XmoPpkreGzHrGvgFPOHPFlzob6r7Fro1Qz/Sghs7cmIMU2quR8i+QX2kryn0QCfqoaTB2mcq40N5g9mR4UjQSdgGQLQA0hOzffxODnOrT4+AcFAseC0P0Js43cBZAgdRQC7vnECh8JC0J/wvW4QtN3v/XxqOMphsSjkbE59bzTplz9b0GxxpimtmNfLIB2uWl9MxySDnMl2hk8AiefhJ4Q5YONxhrqtBLQvizy/mnGOcz6DvDEeZ9inZkHS6dmnn9kMhXhG+nhpPLW7+8U+JwAMXftcMHy+1COhbqqsxkzBRV+aYe6z4kL8qK/Ge9K5tBsDj+8DTkh3bDd/cE8l5+F//7c6fnI=
  api_key:
    secure: hGL3yf0t1ngofsgFZiiFdxTFKpYDRktJjJUG0VI1Gps7QlXLRM9s/JholQ7mMkItGWdYHO6hHTMFgjZuJSUMUzx6pr995Dfg9yNHzRbDhOlJ/+YimNjCchTtjrvJlVIVxOpNecql7++VcgX1MmBhPl686ElNJEerY7ksRtoS5SyOKcWrkV8DHRw8pAnRRHsvUCjDtZOdwaU0c0efWQl9VUT9a3TBPCycpU7hcLDGIquvuX2b4BSEaX6/brujZtegzRhFFhUqVSjvASy/hzfMCEu3p5ivHTsRG12wGNf/RO/U1DkfJuP7rEqHlxj9yhWTwkSYGp63SgYHLo2VR0lxamJ8GbAOQ2o/KzlSNzFbfZ5qnEITAc4g/pZ+4yaRPhQr/Gm//4TwlqKhpAwmjO22hppx5rTZlvNGxQQfhGnkrZ5AzLY4cNGBfeqilkHVDMTdcAlOq4eulAytRQtF7x7uZyE6T4hYHIEYiKr6VHCJ4MUNcZdcc1EcOk0845DQ2X1fGvOlEtHJn6UDIyxTOot/r9TWLwFhaY4DGQZRdweFFwAcruDg4JMaAjXUhafnar+tthlyxgKt0dRb1G+5jzXpKcBRnodIvUJ6dGbUOBnrTytjEB4pUAEa8duGkTmqDWWjwQ7aEePZC1u4sSM3ckgH1A7k9q5r7VFqB2aZiBEaUgE=
